[versions]
ben-manes-versions = "0.42.0"
kotlinter = "3.11.1"

[libraries]
sekvy-composemarkdown = { module = "se.sekvy:compose-markdown", version = "1.0.0-alpha02" }

[bundles]

[plugins]
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
benManesVersions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions" }
